=== RigobertoPO/validaciones-dtd-y-xsd/XSD/AlumnosUnach.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
  <xs:element name="ALUMNOS">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="Alumno"  minOccurs="0" maxOccurs="unbounded">
            <xs:complexType>
              <xs:sequence>
              <xs:element name="Nombre" type="xs:string" />
               <xs:element name="Carrera" type="xs:string" />
                <xs:element name="Calificaciones">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element name="Calificacion" minOccurs="0" maxOccurs="unbounded">
                    <xs:complexType>
                    <xs:sequence>
                        <xs:element name="Materia" type="xs:string" />
                         <xs:element name="Promedio" type="xs:integer" />                     
                    </xs:sequence>                    
                    </xs:complexType>
                    </xs:element>
                  </xs:sequence>                
                </xs:complexType>
                </xs:element>
              </xs:sequence>            
            </xs:complexType>        
        </xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== RigobertoPO/validaciones-dtd-y-xsd/XSD/AlumnosUnach.xml
<?xml version="1.0" encoding="UTF-8"?>
<ALUMNOS xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="file:/D:/Ejemplos/SW/XSD/AlumnosUnach.xsd">
    <Alumno>
      <Nombre>Reynel Perez</Nombre>
      <Carrera>LSC</Carrera>
      <Calificaciones>
        <Calificacion>
          <Materia>Ingenieria de Software 2</Materia>
          <Promedio>9</Promedio>
        </Calificacion>
        <Calificacion>
              <Materia>Servicios Web</Materia>
              <Promedio>10</Promedio>
        </Calificacion>
      </Calificaciones>
    </Alumno>
    
    <Alumno>
      <Nombre>Ana Karen</Nombre>
      <Carrera>Medicina</Carrera>
      <Calificaciones>
          <Calificacion>
            <Materia>Biologia</Materia>
            <Promedio>8</Promedio>
          </Calificacion>      
      </Calificaciones>
    </Alumno>
    <Alumno>
          <Nombre>Juan Jose</Nombre>
        <Carrera>Mecaánica</Carrera>
        <Calificaciones>
            <Calificacion>
              <Materia>Física</Materia>
              <Promedio>10</Promedio>
            </Calificacion>      
        </Calificaciones>
    </Alumno>
</ALUMNOS>
